### ISSUE TITLE
Allow unauthenticated functions

### ISSUE THREAD

**Issue by yonner** [artemrys/google-cloud-functions-deploy#17]
For some reason passing the "--allow-unauthenticated" in the EXTRA_ARGS doesnt work and gives the error : -

`WARNING: Setting IAM policy failed, try "gcloud alpha functions add-iam-policy-binding v1 --region=europe-west1 --member=allUsers --role=roles/cloudfunctions.invoker"`

Would it be possible to add another variable in the pipe : -

"ALLOW_UNAUTHENTICATED" : 'true'

Which defaults to 'false' which calls the above gcloud alpha function, or some how parses the "--allow-unauthenticated" and does the same?

Thank you

Jason

**Comment by artemrys** [comment]
Thanks Jason for the feedback, I'll check it out next week.

**Comment by artemrys** [comment]
@yonner actually, passing `--allow-unauthenticated` works for me, this is my config below. Mind sharing yours so I can reproduce the issue? I am not positive that specifying `--allow-unauthenticated` will help to resolve the issue for you.

```
push: &push
  step:
    name: GCF Deploy
    image: python:3.6.7
    script:
      - pipe: docker://artemrys/google-cloud-functions-deploy:latest
        variables:
          KEY_FILE: $KEY_FILE
          PROJECT: $PROJECT
          FUNCTION_NAME: 'hello_world'
          ENTRY_POINT: 'hello_world'
          RUNTIME: 'python37'
          EXTRA_ARGS: '--allow-unauthenticated'
    services:
    - docker

pipelines:
  branches:
    master:
    - <<: *push
```

**Comment by yonner** [comment]
@artemrys Thanks for the response, my script is pretty much the same as yours : - 

```
- pipe: docker://artemrys/google-cloud-functions-deploy:latest
                variables:
                  KEY_FILE: $KEY_FILE
                  PROJECT: $PROJECT
                  FUNCTION_NAME: 'v1'
                  ENTRY_POINT: 'v1'
                  RUNTIME: 'nodejs14'
                  EXTRA_ARGS: '--region=europe-west1 --env-vars-file env.yaml --allow-unauthenticated'
```

INFO: Starting deployment GCP Cloud Function...
gcloud functions deploy v1 --project=my-project --runtime=nodejs14 --entry-point=v1 --source . --trigger-http --region=europe-west1 --env-vars-file env.yaml --allow-unauthenticated --verbosity=warning
Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
Deploying function (may take a while - up to 2 minutes)...
WARNING: Setting IAM policy failed, try "gcloud alpha functions add-iam-policy-binding v1 --region=europe-west1 --member=allUsers --role=roles/cloudfunctions.invoker"
..............................................................................................................................done.
